FROM --platform=linux/x86_64 mcr.microsoft.com/devcontainers/cpp:1-ubuntu-24.04
# sistema operativo en telf 42
#FROM ubuntu:latest
#
#EXPOSE 80
#
#SHELL ["/bin/bash", "-c"]
#
#VOLUME [ "../" ]
#
#RUN apt-get update && apt-get -y --no-install-recommends install \
#    build-essential \
#    gdb \
#	wget \
#	vim \
#	git \
#	procps \
#	iproute2
#
#CMD ["/bin/bash"]
